<?php

namespace common\models\theaters;

use Yii;

/**
 * This is the model class for table "socials".
 *
 * @property int $id
 * @property string|null $vk
 * @property string|null $facebook
 * @property string|null $instagram
 * @property int|null $movie_theaters_id
 *
 * @property MovieTheaters $movieTheaters
 */
class Socials extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'socials';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['movie_theaters_id'], 'integer'],
            [['vk', 'facebook', 'instagram'], 'string', 'max' => 255],
            [['movie_theaters_id'], 'exist', 'skipOnError' => true, 'targetClass' => MovieTheaters::className(), 'targetAttribute' => ['movie_theaters_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vk' => 'Vk',
            'facebook' => 'Facebook',
            'instagram' => 'Instagram',
            'movie_theaters_id' => 'Movie Theaters ID',
        ];
    }

    /**
     * Gets query for [[MovieTheaters]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMovieTheaters()
    {
        return $this->hasOne(MovieTheaters::className(), ['id' => 'movie_theaters_id']);
    }

    public function save($movie_theaters_id = null, $runValidation = true, $attributeNames = null)
    {
        $this->movie_theaters_id = $movie_theaters_id;
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
